apiVersion: v1
kind: Service
metadata:
  name: app-server-service
  labels: 
    app: app-server
spec:
  type: LoadBalancer
  selector:
    app: app-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
