apiVersion: v1
kind: Service
metadata:
  name: app-server-service
  labels: 
    app: app-server
spec:
  type: NodePort
  selector:
    app: app-server
  ports:
    - nodePort: 30007
      port: 80
      targetPort: 80
