name: Test CI Flow

on:
  push:
    branches: 
      - main
  workflow_dispatch: {}

jobs:



    
  test-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v8

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./Application/TrungNguyenCoffee
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.host.url=${{ secrets.SONAR_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=.
            -Dsonar.verbose=true



      - name: Build and push test Docker image
        working-directory: ./Application/TrungNguyenCoffee
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/swe40006-tn-coffee:${{ github.sha }}
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
          docker push ${{ secrets.DOCKER_USERNAME }}/swe40006-tn-coffee:${{ github.sha }}

  update-manifest:
    runs-on: ubuntu-latest
    needs: test-image

    steps:
      - name: Check out code0
        uses: actions/checkout@v2

      - name: Update Image Tag Values
        run: |
          deployment_file="./k8s/deployment.yaml"  # Update with the actual path to your deployment.yaml
          new_image_tag=${{ github.sha }}

          # Update the deployment.yaml file with the new image tag
          sed -i "s|image: dixluwn/swe40006-tn-coffee:.*|image: ${{ secrets.DOCKER_USERNAME }}/swe40006-tn-coffee:$new_image_tag|" "$deployment_file"

      - name: Update Image Tag Values
        run: |
          deployment_file="./k8s_local/deployment.yaml"  # Update with the actual path to your deployment.yaml
          new_image_tag=${{ github.sha }}
  
          # Update the deployment.yaml file with the new image tag
          sed -i "s|image: dixluwn/swe40006-tn-coffee:.*|image: ${{ secrets.DOCKER_USERNAME }}/swe40006-tn-coffee:$new_image_tag|" "$deployment_file"

      - name: Commit the changes made
        run: | 
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git commit -am "Updating image tag in deployment.yaml"
          git push
